# From: https://mherman.org/blog/dockerizing-a-react-app/

version: '3.7'

services:
  client:
    build:
      context: ${GIT_REPO_ROOT}
      dockerfile: production.Dockerfile
    volumes:
      - ${GIT_REPO_ROOT}:/app
      - /app/node_modules
    ports:
      - 5000:5000
